### ISSUE TITLE
Issue #0001 (Viktor)

### ISSUE THREAD

**Issue by Rettenet** [DrpontAgon/FajlKuldo_P2P#1]
Az IPChangedChecker.cs fájlban a metódust amit adtál (GetLocalIPv4), ha jobban ki tudod kommentelni akkor légyszíves tedd meg, ha nem akkor úgy jelezd hogy eltávolítod a részt a kommentből ahol ugyanerre kérlek.

**Comment by DrpontAgon** [comment]
Szépen kommenteztem.
